### ISSUE TITLE
Compiling module  jsaddle-webkit2gtk-0.8.3.1 gives GI.WebKit2 does not export errors

### ISSUE THREAD

**Issue by hansroland** [ghcjs/jsaddle#22]
Building **jsaddle-webkit2gtk-0.8.3.1** with the appended stack file failes in module **jsaddle-webkit2gtk-0.8.3.1/src/Language/Javascript/JSaddle/WebKitGTK** with several **‘GI.WebKit2’  does not export** error messages. 

The goal is to compile and use reflex-dom with the standard GHC compiler.

Attachments:
* Stack File
* Build Log 

## Stack File

```
flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/reflex-frp/reflex
    commit: 2fe0f566f8d6b6eceb178a85516643390111bb83
  extra-dep: true
- location:
    git: https://github.com/reflex-frp/reflex-dom
    commit: 706ab47df9729bdc5c4ac3f4d8dfd4661d9f6e1a
  subdirs:
  - reflex-dom
  - reflex-dom-core
  extra-dep: true

# Use  dependent-sum-0.3.2.2 from github.
# Version on cabal has wrong base dependency
- location:
    git: https://github.com/mokus0/dependent-sum
    commit: 02173260ce60113ac442da04bf40139119271380 
  extra-dep: true
  
extra-deps:
- ghcjs-dom-0.8.0.0
- ghcjs-dom-jsaddle-0.8.0.0
- jsaddle-0.8.3.2
- jsaddle-dom-0.8.0.0
- jsaddle-webkit2gtk-0.8.3.1
- webkit2gtk3-javascriptcore-0.14.2.1
- gi-webkit2-4.0.12
- gi-javascriptcore-4.0.12
- prim-uniq-0.1.0.1
- ref-tf-0.4.0.1
- zenc-0.1.1
- dependent-sum-template-0.0.0.5
resolver: lts-8.12
```

## Build log

```
dependent-sum-0.3.2.2: configure (lib)
dependent-sum-0.3.2.2: build (lib)
ref-tf-0.4.0.1: configure
ref-tf-0.4.0.1: build
gi-javascriptcore-4.0.12: configure
dependent-sum-0.3.2.2: copy/register
ref-tf-0.4.0.1: copy/register
gi-javascriptcore-4.0.12: build
webkit2gtk3-javascriptcore-0.14.2.1: configure
gi-javascriptcore-4.0.12: copy/register
webkit2gtk3-javascriptcore-0.14.2.1: build
dependent-map-0.2.4.0: configure
dependent-map-0.2.4.0: build
dependent-sum-template-0.0.0.5: configure
dependent-sum-template-0.0.0.5: build
gi-webkit2-4.0.12: configure
dependent-sum-template-0.0.0.5: copy/register
webkit2gtk3-javascriptcore-0.14.2.1: copy/register
dependent-map-0.2.4.0: copy/register
gi-webkit2-4.0.12: build
jsaddle-0.8.3.2: configure
jsaddle-0.8.3.2: build
prim-uniq-0.1.0.1: configure
prim-uniq-0.1.0.1: build
zenc-0.1.1: configure
zenc-0.1.1: build
prim-uniq-0.1.0.1: copy/register
reflex-0.5.0: configure (lib)
zenc-0.1.1: copy/register
reflex-0.5.0: build (lib)
gi-webkit2-4.0.12: copy/register
jsaddle-0.8.3.2: copy/register
jsaddle-webkit2gtk-0.8.3.1: configure
jsaddle-webkit2gtk-0.8.3.1: build
jsaddle-dom-0.8.0.0: configure
jsaddle-dom-0.8.0.0: build
reflex-0.5.0: copy/register
jsaddle-dom-0.8.0.0: copy/register
Progress: 13/18
--  While building package jsaddle-webkit2gtk-0.8.3.1 using:
      /home/roland/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.2.0 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/roland/Projekte/reflex-dom-stack/.stack-work/logs/jsaddle-webkit2gtk-0.8.3.1.log

    Configuring jsaddle-webkit2gtk-0.8.3.1...
    Building jsaddle-webkit2gtk-0.8.3.1...
    Preprocessing library jsaddle-webkit2gtk-0.8.3.1...
    [1 of 1] Compiling Language.Javascript.JSaddle.WebKitGTK ( src/Language/Javascript/JSaddle/WebKitGTK.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/Language/Javascript/JSaddle/WebKitGTK.o )
    
    /tmp/stack1869/jsaddle-webkit2gtk-0.8.3.1/src/Language/Javascript/JSaddle/WebKitGTK.hs:73:9-54: error:
        Module
        ‘GI.WebKit2’
        does not export
        ‘userContentManagerRegisterScriptMessageHandler’
    
    /tmp/stack1869/jsaddle-webkit2gtk-0.8.3.1/src/Language/Javascript/JSaddle/WebKitGTK.hs:76:9-58: error:
        Module
        ‘GI.WebKit2’
        does not export
        ‘mk_UserContentManagerScriptMessageReceivedCallback’
    
    /tmp/stack1869/jsaddle-webkit2gtk-0.8.3.1/src/Language/Javascript/JSaddle/WebKitGTK.hs:77:9-60: error:
        Module
        ‘GI.WebKit2’
        does not export
        ‘wrap_UserContentManagerScriptMessageReceivedCallback’
    
    /tmp/stack1869/jsaddle-webkit2gtk-0.8.3.1/src/Language/Javascript/JSaddle/WebKitGTK.hs:79:9-55: error:
        Module
        ‘GI.WebKit2’
        does not export
        ‘UserContentManagerScriptMessageReceivedCallback’
roland@goms:~/Projekte/reflex-dom-stack$ 
```
